version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8000}
    restart: unless-stopped
    # If you have a backend service, you can uncomment this section
    # depends_on:
    #   - backend

  # Example backend service - uncomment and adjust as needed
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped 